#!/bin/sh

echo -en "Starting installing kuzya into system\t\t\t"
if [ "$LOGNAME" != "root" ]; then
	echo "...failed!"
	echo "You need to be root to run this script"
	exit 1
else
	echo "...please wait!"
fi

echo -en "Making needed dirs\t\t\t\t\t"
if mkdir -p /usr/share/kuzya 	>/root/ierror	&&
mkdir -p /usr/share/kuzya/bin	>/root/ierror	&&
mkdir -p /usr/bin		>/root/ierror	&&
mkdir -p /usr/doc/kuzya		>/root/ierror	&&
mkdir -p /usr/include/kuzya	>/root/ierror	&&
mkdir -p /usr/share/kuzya/resources/translations; then
	echo "...ok!"
else
	echo "...error!"
	echo &2
	cat /root/ierror
	exit 1
fi

echo -en "Copying needed files\t\t\t\t\t"
if cp -f ./graphics/c/graphics.h /usr/include/kuzya/	2>/root/ierror	&&
cp -fr ./doc /usr/doc/kuzya				2>/root/ierror 	&&
cp -fr ./profiles /usr/share/kuzya/			2>/root/ierror 	&&
cp -fr ./resources /usr/share/kuzya/			2>/root/ierror 	&&
cp -fr ./src/images /usr/share/kuzya/src/		2>/root/ierror 	&&
cp -fr ./resources/qss /usr/share/kuzya/resources/	2>/root/ierror; then
	echo "...ok!"
else
	echo "...error!"
	cat /root/ierror
	exit 1
fi

echo -en "Instiling kuzya into the system\t\t\t\t"
if install -Dpm 755 ../bin/kuzyagraph /usr/bin/kuzyagraph			>/root/ierror	&&
install -Dpm 755 ../bin/kuzya      /usr/bin/kuzya					>/root/ierror  &&
install -Dpm 755 ./resources/translations/*.qm /usr/share/kuzya/src/translations	>/root/ierror; then
	echo "...ok!"
else
	echo "...error!"
	cat /root/ierror
	exit 1
fi

rm -f /root/ierror
	echo "Kuzya was successfully installied!"
